
version: '3'

services:
    
    #service 1: database
    db_cv:
      image: mysql:latest
      hostname: db_cv
      container_name: db_cv
      environment:
        MYSQL_DATABASE: 'cv'
        MYSQL_USER: 'cv'
        MYSQL_PASSWORD: 'cv'
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_ROOT_HOST: '%'
      ports:
        - "3306:3306"
      restart: always
      
    
    
    #service 2 : image de l'application
    cv:                        
      image: cvimage               #nom de l'image 
      container_name: cv-app  #Nom du conteneur 
      build:
        context: .                          #docker location
        dockerfile: Dockerfile              
      ports:
        - "8081:8081"  
      links:
      - db_cv:db_cv
      environment: #les varriables d'environement spring
        SPRING_DATASOURCE_URL: jdbc:mysql://db_cv:3306/cv        
        SPRING_DATASOURCE_USERNAME: cv
        SPRING_DATASOURCE_PASSWORD: cv    
      restart: always
        
      depends_on:                           
        - db_cv                                #Cette image depend de l'image precedente de la base de données
      